import {
  ArrowDown,
  ArrowUp,
  Baby,
  Banknote,
  Beer,
  Bike,
  Bitcoin,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Camera,
  Car,
  CarTaxiFront,
  Church,
  CircleDollarSign,
  Clapperboard,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Dog,
  Dumbbell,
  Flower,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  HousePlus,
  IceCream,
  Landmark,
  Laptop,
  Martini,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Receipt,
  Sandwich,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Soup,
  Sparkles,
  Stethoscope,
  Sun,
  TentTree,
  Ticket,
  TrainFront,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  WashingMachine,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type CategoryIconDef = {
  name: string;
  label: string;
  Icon: LucideIcon;
  aliases?: string[];
};

export const CATEGORY_ICONS: CategoryIconDef[] = [
  {
    name: "income",
    label: "Income",
    Icon: ArrowUp,
    aliases: ["earning", "revenue", "arrow-up", "ArrowUpIcon"],
  },
  {
    name: "expense",
    label: "Expense",
    Icon: ArrowDown,
    aliases: ["cost", "spending", "arrow-down", "ArrowDownIcon"],
  },
  {
    name: "salary",
    label: "Salary",
    Icon: Briefcase,
    aliases: ["payroll", "job", "BriefcaseIcon"],
  },
  {
    name: "freelance",
    label: "Freelance",
    Icon: Laptop,
    aliases: ["contract", "developer", "LaptopIcon"],
  },
  {
    name: "business",
    label: "Business",
    Icon: Landmark,
    aliases: ["company", "office", "LandmarkIcon"],
  },
  {
    name: "investment",
    label: "Investment",
    Icon: TrendingUp,
    aliases: ["portfolio", "stocks", "TrendingUpIcon"],
  },
  {
    name: "investment-loss",
    label: "Investment Loss",
    Icon: TrendingDown,
    aliases: ["loss", "downtrend", "TrendingDownIcon"],
  },
  {
    name: "bonus",
    label: "Bonus",
    Icon: Coins,
    aliases: ["reward", "extra", "CoinsIcon"],
  },
  {
    name: "refund",
    label: "Refund",
    Icon: Wallet,
    aliases: ["cashback", "reimbursement", "WalletIcon"],
  },
  {
    name: "savings",
    label: "Savings",
    Icon: PiggyBank,
    aliases: ["save", "piggy-bank", "PiggyBankIcon"],
  },
  {
    name: "debt",
    label: "Debt",
    Icon: HandCoins,
    aliases: ["loan", "credit", "HandCoinsIcon"],
  },
  {
    name: "rent",
    label: "Rent",
    Icon: Home,
    aliases: ["housing", "home", "HomeIcon"],
  },
  {
    name: "mortgage",
    label: "Mortgage",
    Icon: HousePlus,
    aliases: ["house-plus", "HousePlusIcon"],
  },
  {
    name: "home-maintenance",
    label: "Home Maintenance",
    Icon: Wrench,
    aliases: ["repair", "maintenance", "WrenchIcon"],
  },
  {
    name: "utilities",
    label: "Utilities",
    Icon: Wifi,
    aliases: ["utility", "services", "WifiIcon"],
  },
  {
    name: "electricity",
    label: "Electricity",
    Icon: Zap,
    aliases: ["power", "energy", "ZapIcon"],
  },
  {
    name: "water",
    label: "Water",
    Icon: Waves,
    aliases: ["waves", "WavesIcon"],
  },
  {
    name: "phone",
    label: "Phone",
    Icon: Smartphone,
    aliases: ["mobile", "SmartphoneIcon"],
  },
  {
    name: "groceries",
    label: "Groceries",
    Icon: ShoppingCart,
    aliases: ["supermarket", "ShoppingCartIcon"],
  },
  {
    name: "food",
    label: "Food",
    Icon: Utensils,
    aliases: ["meal", "dining", "UtensilsIcon"],
  },
  {
    name: "dining",
    label: "Dining Out",
    Icon: Soup,
    aliases: ["restaurant", "lunch", "dinner", "SoupIcon"],
  },
  {
    name: "coffee",
    label: "Coffee",
    Icon: Coffee,
    aliases: ["cafe", "CoffeeIcon"],
  },
  {
    name: "transport",
    label: "Transport",
    Icon: Bus,
    aliases: ["transportation", "bus", "BusIcon"],
  },
  {
    name: "fuel",
    label: "Fuel",
    Icon: Fuel,
    aliases: ["gas", "gasoline", "petrol", "FuelIcon"],
  },
  {
    name: "car",
    label: "Car",
    Icon: Car,
    aliases: ["vehicle", "CarIcon"],
  },
  {
    name: "taxi",
    label: "Taxi",
    Icon: CarTaxiFront,
    aliases: ["uber", "cab", "CarTaxiFrontIcon"],
  },
  {
    name: "public-transport",
    label: "Public Transport",
    Icon: TrainFront,
    aliases: ["train", "metro", "TrainFrontIcon"],
  },
  {
    name: "travel",
    label: "Travel",
    Icon: Plane,
    aliases: ["trip", "flight", "PlaneIcon"],
  },
  {
    name: "hotel",
    label: "Hotel",
    Icon: Umbrella,
    aliases: ["stay", "accommodation", "UmbrellaIcon"],
  },
  {
    name: "shopping",
    label: "Shopping",
    Icon: ShoppingBag,
    aliases: ["store", "ShoppingBagIcon"],
  },
  {
    name: "clothing",
    label: "Clothing",
    Icon: Shirt,
    aliases: ["apparel", "ShirtIcon"],
  },
  {
    name: "gift",
    label: "Gift",
    Icon: Gift,
    aliases: ["present", "GiftIcon"],
  },
  {
    name: "subscription",
    label: "Subscription",
    Icon: CreditCard,
    aliases: ["recurring", "CreditCardIcon"],
  },
  {
    name: "entertainment",
    label: "Entertainment",
    Icon: Clapperboard,
    aliases: ["movie", "cinema", "ClapperboardIcon"],
  },
  {
    name: "streaming",
    label: "Streaming",
    Icon: Tv,
    aliases: ["tv", "TvIcon"],
  },
  {
    name: "gaming",
    label: "Gaming",
    Icon: Gamepad2,
    aliases: ["games", "Gamepad2Icon"],
  },
  {
    name: "events",
    label: "Events",
    Icon: Ticket,
    aliases: ["tickets", "concert", "TicketIcon"],
  },
  {
    name: "health",
    label: "Health",
    Icon: HeartPulse,
    aliases: ["medical", "clinic", "HeartPulseIcon"],
  },
  {
    name: "fitness",
    label: "Fitness",
    Icon: Dumbbell,
    aliases: ["gym", "workout", "DumbbellIcon"],
  },
  {
    name: "insurance",
    label: "Insurance",
    Icon: Shield,
    aliases: ["coverage", "ShieldIcon"],
  },
  {
    name: "education",
    label: "Education",
    Icon: GraduationCap,
    aliases: ["school", "study", "GraduationCapIcon"],
  },
  {
    name: "books",
    label: "Books",
    Icon: BookOpen,
    aliases: ["book", "reading", "BookOpenIcon"],
  },
  {
    name: "taxes",
    label: "Taxes",
    Icon: Receipt,
    aliases: ["tax", "ReceiptIcon"],
  },
  {
    name: "social",
    label: "Social",
    Icon: Users,
    aliases: ["friends", "community", "UsersIcon"],
  },
  {
    name: "family",
    label: "Family",
    Icon: Users,
    aliases: ["household"],
  },
  {
    name: "pets",
    label: "Pets",
    Icon: PawPrint,
    aliases: ["pet", "PawPrintIcon"],
  },
  {
    name: "work",
    label: "Work",
    Icon: Building2,
    aliases: ["office-building", "Building2Icon"],
  },
  {
    name: "personal-care",
    label: "Personal Care",
    Icon: Scissors,
    aliases: [
      "beauty",
      "haircut",
      "salon",
      "barber",
      "cabello",
      "peluqueria",
      "estetica",
      "belleza",
      "ScissorsIcon",
    ],
  },
  {
    name: "alcohol",
    label: "Alcohol",
    Icon: Wine,
    aliases: ["wine", "vino", "bar", "drinks", "WineIcon"],
  },
  {
    name: "beer",
    label: "Beer",
    Icon: Beer,
    aliases: ["cerveza", "pub", "BeerIcon"],
  },
  {
    name: "cocktails",
    label: "Cocktails",
    Icon: Martini,
    aliases: ["coctel", "drinks", "nightlife", "MartiniIcon"],
  },
  {
    name: "snacks",
    label: "Snacks",
    Icon: Cookie,
    aliases: ["sweets", "dulces", "galletas", "CookieIcon"],
  },
  {
    name: "fast-food",
    label: "Fast Food",
    Icon: Sandwich,
    aliases: ["burger", "sandwich", "comida-rapida", "SandwichIcon"],
  },
  {
    name: "pizza",
    label: "Pizza",
    Icon: Pizza,
    aliases: ["PizzaIcon"],
  },
  {
    name: "ice-cream",
    label: "Ice Cream",
    Icon: IceCream,
    aliases: ["dessert", "helado", "postre", "IceCreamIcon"],
  },
  {
    name: "bakery",
    label: "Bakery",
    Icon: Cake,
    aliases: ["cake", "pastry", "panaderia", "pasteleria", "CakeIcon"],
  },
  {
    name: "movies",
    label: "Movies",
    Icon: Popcorn,
    aliases: ["cinema", "cine", "peliculas", "PopcornIcon"],
  },
  {
    name: "music",
    label: "Music",
    Icon: Music,
    aliases: ["musica", "MusicIcon"],
  },
  {
    name: "audio",
    label: "Audio",
    Icon: Headphones,
    aliases: ["headphones", "audifonos", "HeadphonesIcon"],
  },
  {
    name: "photography",
    label: "Photography",
    Icon: Camera,
    aliases: ["camera", "photo", "fotografia", "CameraIcon"],
  },
  {
    name: "hardware",
    label: "Hardware",
    Icon: Hammer,
    aliases: ["tools", "herramientas", "HammerIcon"],
  },
  {
    name: "parking",
    label: "Parking",
    Icon: ParkingCircle,
    aliases: ["estacionamiento", "ParkingCircleIcon"],
  },
  {
    name: "bike",
    label: "Bike",
    Icon: Bike,
    aliases: ["bicycle", "bicicleta", "cycling", "BikeIcon"],
  },
  {
    name: "pharmacy",
    label: "Pharmacy",
    Icon: Pill,
    aliases: ["medicine", "medicina", "drugs", "farmacia", "PillIcon"],
  },
  {
    name: "doctor",
    label: "Doctor",
    Icon: Stethoscope,
    aliases: ["clinic", "medico", "consulta", "StethoscopeIcon"],
  },
  {
    name: "cryptocurrency",
    label: "Cryptocurrency",
    Icon: Bitcoin,
    aliases: ["crypto", "btc", "BitcoinIcon"],
  },
  {
    name: "dividends",
    label: "Dividends",
    Icon: CircleDollarSign,
    aliases: ["interest", "intereses", "dividendos", "CircleDollarSignIcon"],
  },
  {
    name: "cash",
    label: "Cash",
    Icon: Banknote,
    aliases: ["atm", "withdrawal", "efectivo", "retiro", "BanknoteIcon"],
  },
  {
    name: "charity",
    label: "Charity",
    Icon: Heart,
    aliases: ["donation", "donations", "donacion", "caridad", "HeartIcon"],
  },
  {
    name: "church",
    label: "Church",
    Icon: Church,
    aliases: ["religion", "tithe", "iglesia", "diezmo", "ChurchIcon"],
  },
  {
    name: "kids",
    label: "Kids",
    Icon: Baby,
    aliases: ["children", "baby", "ninos", "bebe", "BabyIcon"],
  },
  {
    name: "pet-supplies",
    label: "Pet Supplies",
    Icon: Dog,
    aliases: ["dog", "perro", "mascota", "DogIcon"],
  },
  {
    name: "garden",
    label: "Garden",
    Icon: Flower,
    aliases: ["plants", "jardin", "plantas", "FlowerIcon"],
  },
  {
    name: "outdoors",
    label: "Outdoors",
    Icon: Mountain,
    aliases: ["hiking", "nature", "naturaleza", "MountainIcon"],
  },
  {
    name: "camping",
    label: "Camping",
    Icon: TentTree,
    aliases: ["acampar", "TentTreeIcon"],
  },
  {
    name: "sports",
    label: "Sports",
    Icon: Trophy,
    aliases: ["sport", "deportes", "TrophyIcon"],
  },
  {
    name: "stationery",
    label: "Stationery",
    Icon: Notebook,
    aliases: ["office-supplies", "papeleria", "NotebookIcon"],
  },
  {
    name: "news",
    label: "News",
    Icon: Newspaper,
    aliases: ["magazines", "noticias", "periodico", "NewspaperIcon"],
  },
  {
    name: "celebration",
    label: "Celebration",
    Icon: PartyPopper,
    aliases: ["party", "birthday", "fiesta", "cumpleanos", "PartyPopperIcon"],
  },
  {
    name: "cleaning",
    label: "Cleaning",
    Icon: WashingMachine,
    aliases: ["laundry", "limpieza", "lavanderia", "WashingMachineIcon"],
  },
  {
    name: "internet",
    label: "Internet",
    Icon: Globe,
    aliases: ["online", "web", "GlobeIcon"],
  },
  {
    name: "tip",
    label: "Tip",
    Icon: Sparkles,
    aliases: ["gratuity", "propina", "tips", "SparklesIcon"],
  },
  { name: "other", label: "Other", Icon: Sun, aliases: ["misc", "SunIcon"] },
];
