import type { LucideIcon } from "lucide-react";
import {
  ArrowDown,
  ArrowUp,
  Baby,
  Banknote,
  Beer,
  Bike,
  Bitcoin,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Camera,
  Car,
  CarTaxiFront,
  Church,
  CircleDollarSign,
  Clapperboard,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Dog,
  Dumbbell,
  Flower,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  HousePlus,
  IceCream,
  Landmark,
  Laptop,
  Martini,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Receipt,
  Sandwich,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Soup,
  Sparkles,
  Stethoscope,
  Sun,
  TentTree,
  Ticket,
  TrainFront,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  WashingMachine,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export interface CategoryIconDef {
  aliases?: string[];
  Icon: LucideIcon;
  label: string;
  name: string;
}

export const CATEGORY_ICONS: CategoryIconDef[] = [
  {
    aliases: ["earning", "revenue", "arrow-up", "ArrowUpIcon"],
    Icon: ArrowUp,
    label: "Income",
    name: "income",
  },
  {
    aliases: ["cost", "spending", "arrow-down", "ArrowDownIcon"],
    Icon: ArrowDown,
    label: "Expense",
    name: "expense",
  },
  {
    aliases: ["payroll", "job", "BriefcaseIcon"],
    Icon: Briefcase,
    label: "Salary",
    name: "salary",
  },
  {
    aliases: ["contract", "developer", "LaptopIcon"],
    Icon: Laptop,
    label: "Freelance",
    name: "freelance",
  },
  {
    aliases: ["company", "office", "LandmarkIcon"],
    Icon: Landmark,
    label: "Business",
    name: "business",
  },
  {
    aliases: ["portfolio", "stocks", "TrendingUpIcon"],
    Icon: TrendingUp,
    label: "Investment",
    name: "investment",
  },
  {
    aliases: ["loss", "downtrend", "TrendingDownIcon"],
    Icon: TrendingDown,
    label: "Investment Loss",
    name: "investment-loss",
  },
  {
    aliases: ["reward", "extra", "CoinsIcon"],
    Icon: Coins,
    label: "Bonus",
    name: "bonus",
  },
  {
    aliases: ["cashback", "reimbursement", "WalletIcon"],
    Icon: Wallet,
    label: "Refund",
    name: "refund",
  },
  {
    aliases: ["save", "piggy-bank", "PiggyBankIcon"],
    Icon: PiggyBank,
    label: "Savings",
    name: "savings",
  },
  {
    aliases: ["loan", "credit", "HandCoinsIcon"],
    Icon: HandCoins,
    label: "Debt",
    name: "debt",
  },
  {
    aliases: ["housing", "home", "HomeIcon"],
    Icon: Home,
    label: "Rent",
    name: "rent",
  },
  {
    aliases: ["house-plus", "HousePlusIcon"],
    Icon: HousePlus,
    label: "Mortgage",
    name: "mortgage",
  },
  {
    aliases: ["repair", "maintenance", "WrenchIcon"],
    Icon: Wrench,
    label: "Home Maintenance",
    name: "home-maintenance",
  },
  {
    aliases: ["utility", "services", "WifiIcon"],
    Icon: Wifi,
    label: "Utilities",
    name: "utilities",
  },
  {
    aliases: ["power", "energy", "ZapIcon"],
    Icon: Zap,
    label: "Electricity",
    name: "electricity",
  },
  {
    aliases: ["waves", "WavesIcon"],
    Icon: Waves,
    label: "Water",
    name: "water",
  },
  {
    aliases: ["mobile", "SmartphoneIcon"],
    Icon: Smartphone,
    label: "Phone",
    name: "phone",
  },
  {
    aliases: ["supermarket", "ShoppingCartIcon"],
    Icon: ShoppingCart,
    label: "Groceries",
    name: "groceries",
  },
  {
    aliases: ["meal", "dining", "UtensilsIcon"],
    Icon: Utensils,
    label: "Food",
    name: "food",
  },
  {
    aliases: ["restaurant", "lunch", "dinner", "SoupIcon"],
    Icon: Soup,
    label: "Dining Out",
    name: "dining",
  },
  {
    aliases: ["cafe", "CoffeeIcon"],
    Icon: Coffee,
    label: "Coffee",
    name: "coffee",
  },
  {
    aliases: ["transportation", "bus", "BusIcon"],
    Icon: Bus,
    label: "Transport",
    name: "transport",
  },
  {
    aliases: ["gas", "gasoline", "petrol", "FuelIcon"],
    Icon: Fuel,
    label: "Fuel",
    name: "fuel",
  },
  {
    aliases: ["vehicle", "CarIcon"],
    Icon: Car,
    label: "Car",
    name: "car",
  },
  {
    aliases: ["uber", "cab", "CarTaxiFrontIcon"],
    Icon: CarTaxiFront,
    label: "Taxi",
    name: "taxi",
  },
  {
    aliases: ["train", "metro", "TrainFrontIcon"],
    Icon: TrainFront,
    label: "Public Transport",
    name: "public-transport",
  },
  {
    aliases: ["trip", "flight", "PlaneIcon"],
    Icon: Plane,
    label: "Travel",
    name: "travel",
  },
  {
    aliases: ["stay", "accommodation", "UmbrellaIcon"],
    Icon: Umbrella,
    label: "Hotel",
    name: "hotel",
  },
  {
    aliases: ["store", "ShoppingBagIcon"],
    Icon: ShoppingBag,
    label: "Shopping",
    name: "shopping",
  },
  {
    aliases: ["apparel", "ShirtIcon"],
    Icon: Shirt,
    label: "Clothing",
    name: "clothing",
  },
  {
    aliases: ["present", "GiftIcon"],
    Icon: Gift,
    label: "Gift",
    name: "gift",
  },
  {
    aliases: ["recurring", "CreditCardIcon"],
    Icon: CreditCard,
    label: "Subscription",
    name: "subscription",
  },
  {
    aliases: ["movie", "cinema", "ClapperboardIcon"],
    Icon: Clapperboard,
    label: "Entertainment",
    name: "entertainment",
  },
  {
    aliases: ["tv", "TvIcon"],
    Icon: Tv,
    label: "Streaming",
    name: "streaming",
  },
  {
    aliases: ["games", "Gamepad2Icon"],
    Icon: Gamepad2,
    label: "Gaming",
    name: "gaming",
  },
  {
    aliases: ["tickets", "concert", "TicketIcon"],
    Icon: Ticket,
    label: "Events",
    name: "events",
  },
  {
    aliases: ["medical", "clinic", "HeartPulseIcon"],
    Icon: HeartPulse,
    label: "Health",
    name: "health",
  },
  {
    aliases: ["gym", "workout", "DumbbellIcon"],
    Icon: Dumbbell,
    label: "Fitness",
    name: "fitness",
  },
  {
    aliases: ["coverage", "ShieldIcon"],
    Icon: Shield,
    label: "Insurance",
    name: "insurance",
  },
  {
    aliases: ["school", "study", "GraduationCapIcon"],
    Icon: GraduationCap,
    label: "Education",
    name: "education",
  },
  {
    aliases: ["book", "reading", "BookOpenIcon"],
    Icon: BookOpen,
    label: "Books",
    name: "books",
  },
  {
    aliases: ["tax", "ReceiptIcon"],
    Icon: Receipt,
    label: "Taxes",
    name: "taxes",
  },
  {
    aliases: ["friends", "community", "UsersIcon"],
    Icon: Users,
    label: "Social",
    name: "social",
  },
  {
    aliases: ["household"],
    Icon: Users,
    label: "Family",
    name: "family",
  },
  {
    aliases: ["pet", "PawPrintIcon"],
    Icon: PawPrint,
    label: "Pets",
    name: "pets",
  },
  {
    aliases: ["office-building", "Building2Icon"],
    Icon: Building2,
    label: "Work",
    name: "work",
  },
  {
    aliases: [
      "beauty",
      "haircut",
      "salon",
      "barber",
      "cabello",
      "peluqueria",
      "estetica",
      "belleza",
      "ScissorsIcon",
    ],
    Icon: Scissors,
    label: "Personal Care",
    name: "personal-care",
  },
  {
    aliases: ["wine", "vino", "bar", "drinks", "WineIcon"],
    Icon: Wine,
    label: "Alcohol",
    name: "alcohol",
  },
  {
    aliases: ["cerveza", "pub", "BeerIcon"],
    Icon: Beer,
    label: "Beer",
    name: "beer",
  },
  {
    aliases: ["coctel", "drinks", "nightlife", "MartiniIcon"],
    Icon: Martini,
    label: "Cocktails",
    name: "cocktails",
  },
  {
    aliases: ["sweets", "dulces", "galletas", "CookieIcon"],
    Icon: Cookie,
    label: "Snacks",
    name: "snacks",
  },
  {
    aliases: ["burger", "sandwich", "comida-rapida", "SandwichIcon"],
    Icon: Sandwich,
    label: "Fast Food",
    name: "fast-food",
  },
  {
    aliases: ["PizzaIcon"],
    Icon: Pizza,
    label: "Pizza",
    name: "pizza",
  },
  {
    aliases: ["dessert", "helado", "postre", "IceCreamIcon"],
    Icon: IceCream,
    label: "Ice Cream",
    name: "ice-cream",
  },
  {
    aliases: ["cake", "pastry", "panaderia", "pasteleria", "CakeIcon"],
    Icon: Cake,
    label: "Bakery",
    name: "bakery",
  },
  {
    aliases: ["cinema", "cine", "peliculas", "PopcornIcon"],
    Icon: Popcorn,
    label: "Movies",
    name: "movies",
  },
  {
    aliases: ["musica", "MusicIcon"],
    Icon: Music,
    label: "Music",
    name: "music",
  },
  {
    aliases: ["headphones", "audifonos", "HeadphonesIcon"],
    Icon: Headphones,
    label: "Audio",
    name: "audio",
  },
  {
    aliases: ["camera", "photo", "fotografia", "CameraIcon"],
    Icon: Camera,
    label: "Photography",
    name: "photography",
  },
  {
    aliases: ["tools", "herramientas", "HammerIcon"],
    Icon: Hammer,
    label: "Hardware",
    name: "hardware",
  },
  {
    aliases: ["estacionamiento", "ParkingCircleIcon"],
    Icon: ParkingCircle,
    label: "Parking",
    name: "parking",
  },
  {
    aliases: ["bicycle", "bicicleta", "cycling", "BikeIcon"],
    Icon: Bike,
    label: "Bike",
    name: "bike",
  },
  {
    aliases: ["medicine", "medicina", "drugs", "farmacia", "PillIcon"],
    Icon: Pill,
    label: "Pharmacy",
    name: "pharmacy",
  },
  {
    aliases: ["clinic", "medico", "consulta", "StethoscopeIcon"],
    Icon: Stethoscope,
    label: "Doctor",
    name: "doctor",
  },
  {
    aliases: ["crypto", "btc", "BitcoinIcon"],
    Icon: Bitcoin,
    label: "Cryptocurrency",
    name: "cryptocurrency",
  },
  {
    aliases: ["interest", "intereses", "dividendos", "CircleDollarSignIcon"],
    Icon: CircleDollarSign,
    label: "Dividends",
    name: "dividends",
  },
  {
    aliases: ["atm", "withdrawal", "efectivo", "retiro", "BanknoteIcon"],
    Icon: Banknote,
    label: "Cash",
    name: "cash",
  },
  {
    aliases: ["donation", "donations", "donacion", "caridad", "HeartIcon"],
    Icon: Heart,
    label: "Charity",
    name: "charity",
  },
  {
    aliases: ["religion", "tithe", "iglesia", "diezmo", "ChurchIcon"],
    Icon: Church,
    label: "Church",
    name: "church",
  },
  {
    aliases: ["children", "baby", "ninos", "bebe", "BabyIcon"],
    Icon: Baby,
    label: "Kids",
    name: "kids",
  },
  {
    aliases: ["dog", "perro", "mascota", "DogIcon"],
    Icon: Dog,
    label: "Pet Supplies",
    name: "pet-supplies",
  },
  {
    aliases: ["plants", "jardin", "plantas", "FlowerIcon"],
    Icon: Flower,
    label: "Garden",
    name: "garden",
  },
  {
    aliases: ["hiking", "nature", "naturaleza", "MountainIcon"],
    Icon: Mountain,
    label: "Outdoors",
    name: "outdoors",
  },
  {
    aliases: ["acampar", "TentTreeIcon"],
    Icon: TentTree,
    label: "Camping",
    name: "camping",
  },
  {
    aliases: ["sport", "deportes", "TrophyIcon"],
    Icon: Trophy,
    label: "Sports",
    name: "sports",
  },
  {
    aliases: ["office-supplies", "papeleria", "NotebookIcon"],
    Icon: Notebook,
    label: "Stationery",
    name: "stationery",
  },
  {
    aliases: ["magazines", "noticias", "periodico", "NewspaperIcon"],
    Icon: Newspaper,
    label: "News",
    name: "news",
  },
  {
    aliases: ["party", "birthday", "fiesta", "cumpleanos", "PartyPopperIcon"],
    Icon: PartyPopper,
    label: "Celebration",
    name: "celebration",
  },
  {
    aliases: ["laundry", "limpieza", "lavanderia", "WashingMachineIcon"],
    Icon: WashingMachine,
    label: "Cleaning",
    name: "cleaning",
  },
  {
    aliases: ["online", "web", "GlobeIcon"],
    Icon: Globe,
    label: "Internet",
    name: "internet",
  },
  {
    aliases: ["gratuity", "propina", "tips", "SparklesIcon"],
    Icon: Sparkles,
    label: "Tip",
    name: "tip",
  },
  { aliases: ["misc", "SunIcon"], Icon: Sun, label: "Other", name: "other" },
];
