allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - msw
  - prisma
  - unrs-resolver
