allowBuilds:
  "@parcel/watcher": set this to true or false
  "@prisma/client": set this to true or false
  "@prisma/engines": true
  bcrypt: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - prettier-plugin-tailwindcss@0.8.1
onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - msw
  - prisma
  - unrs-resolver
